import pygame
from keys import *

KEY_NOTE_MAP = {
    K_TAB: 'B3',
    K_q: 'C4',
    K_2: 'C#4',
    K_w: 'D4',
    K_3: 'D#4',
    K_e: 'E4',
    K_r: 'F4',
    K_5: 'F#4',
    K_t: 'G4',
    K_6: 'G#4',
    K_y: 'A4',
    K_7: 'A#4',
    K_u: 'B4',
    K_i: 'C5',
    K_9: 'C#5',
    K_o: 'D5',
    K_0: 'D#5',
    K_p: 'E5',
    K_z: 'F5',
    K_s: 'F#5',
    K_x: 'G5',
    K_d: 'G#5',
    K_c: 'A5',
    K_f: 'A#5',
    K_v: 'B5',
    K_b: 'C6',
    K_h: 'C#6',
    K_n: 'D6',
    K_j: 'D#6',
    K_m: 'E6',
    K_COMMA: 'F6',
    K_l: 'F#6',
    K_PERIOD: 'G6',
    KSCAN_RGUI: 'G#6',
    K_SEMICOLON: 'A6',
    K_RSHIFT: 'B6',
}

